# Generated by Django 4.0.2 on 2022-03-20 17:59

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import users.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
        ('municipality', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('lastname', models.CharField(blank=True, max_length=30, verbose_name='Фамилия')),
                ('firstname', models.CharField(blank=True, max_length=30, verbose_name='Имя')),
                ('middlename', models.CharField(blank=True, max_length=30, verbose_name='Отчество')),
                ('gender', models.CharField(choices=[(1, 'женский'), (2, 'мужской')], default=2, max_length=10, verbose_name='Пол')),
                ('date_of_birth', models.DateField(auto_now_add=True, verbose_name='Дата рождения')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Телефон')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Суперпользователь')),
                ('is_archive', models.BooleanField(default=False, verbose_name='Пользователь в архиве')),
                ('avatar', models.ImageField(blank=True, upload_to='users/avatars', verbose_name='Аватар пользователя')),
                ('avatar_small', models.ImageField(blank=True, upload_to='thumbs', verbose_name='Аватар пользователя thumb')),
                ('marital_status', models.CharField(choices=[(1, 'замужем/женат'), (2, 'холост/не замужем]')], default=2, max_length=55, verbose_name='Семейное положение')),
                ('is_has_childrens', models.BooleanField(default=False, verbose_name='Дети есть/нет')),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('groups', models.ManyToManyField(blank=True, related_name='user_groups', to='auth.Group', verbose_name='Группы пользователя')),
                ('mo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='municipality.municipality', verbose_name='Муниципальное образование пользователя')),
                ('property_address', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_address', to='address.addressinfo', verbose_name='Адрес собственности')),
                ('registration_address', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='registration_address', to='address.addressinfo', verbose_name='Адрес регистрации')),
                ('residential_address', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='residential_address', to='address.addressinfo', verbose_name='Адрес проживания')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
            managers=[
                ('objects', users.managers.UserManager()),
            ],
        ),
    ]
