# Generated by Django 4.0.2 on 2022-03-20 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='property_address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_address', to='address.addressinfo', verbose_name='Адрес собственности'),
        ),
        migrations.AlterField(
            model_name='user',
            name='registration_address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registration_address', to='address.addressinfo', verbose_name='Адрес регистрации'),
        ),
        migrations.AlterField(
            model_name='user',
            name='residential_address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='residential_address', to='address.addressinfo', verbose_name='Адрес проживания'),
        ),
    ]
