version: '3.1'

services:
  db:
    image: postgres
    restart: always
    container_name: 'citizen_db'
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "1234"
      POSTGRES_USER: "citizen"
      POSTGRES_DB: "citizen_db"
    ports:
      - 5432:5432

volumes:
  db: