# Generated by Django 4.0.2 on 2022-03-20 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problem', '0001_initial'),
        ('address', '0001_initial'),
        ('municipality', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemlikedislike',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='problemlikedislike',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem.problem', verbose_name='Проблема'),
        ),
        migrations.AddField(
            model_name='problemhistory',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem.problem', verbose_name='Проблема'),
        ),
        migrations.AddField(
            model_name='problemcomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='problemcomment',
            name='parent_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='problem.problemcomment', verbose_name='Родительский комментарий'),
        ),
        migrations.AddField(
            model_name='problemcomment',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem.problem', verbose_name='Проблема'),
        ),
        migrations.AddField(
            model_name='problemcomment',
            name='problem_additional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='problem.problemadditional', verbose_name='Прикреппить к дополнению'),
        ),
        migrations.AddField(
            model_name='problemcategory',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='problem.problemcategory', verbose_name='Родительская категория'),
        ),
        migrations.AddField(
            model_name='problemadditional',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='problemadditional',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem.problem', verbose_name='Проблема'),
        ),
        migrations.AddField(
            model_name='problem',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='address.addressinfo', verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='problem',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='problem_authors', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='problem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problem_category', to='problem.problemcategory', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='problem',
            name='mo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='municipality.municipality', verbose_name='МО'),
        ),
        migrations.AddField(
            model_name='problem',
            name='operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problem_operators', to=settings.AUTH_USER_MODEL, verbose_name='Оператор принявший проблему'),
        ),
        migrations.AddField(
            model_name='problem',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problem_subcategory', to='problem.problemcategory', verbose_name='Под категория'),
        ),
    ]
