# Generated by Django 4.0.2 on 2022-03-21 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problemcomment',
            name='problem_additional',
        ),
    ]
